dist: bionic
language: minimal
addons:
  apt:
    packages:
    - portaudio19-dev
    - sox
install:
- curl https://bootstrap.pypa.io/get-pip.py | sudo python3
- pip3 install --user pyven
env:
- HEADS=true
- HEADS=false
script: travis_ci
